### ISSUE TITLE
求助Error: Command failed: regsvr32

### ISSUE THREAD

**Issue by plus1998** [aweiu/dm.dll#8]
我在Electron中运行，已经rebuild过了 node 12.18.3-x86 Electron 9.1.0 运行时出现问题

`[ele] Error: Command failed: regsvr32 D:\workspace\qqsg_dm_electron\node_modules\dm.dll\dist\dm.dll /s
[ele]     at checkExecSyncError (child_process.js:630:11)
[ele]     at Object.execSync (child_process.js:666:15)
[ele]     at Object.execSync (electron/js2c/asar.js:727:23)
[ele]     at getDM (D:\workspace\qqsg_dm_electron\node_modules\dm.dll\dist\index.js:10:25)
[ele]     at Object.<anonymous> (D:\workspace\qqsg_dm_electron\node_modules\dm.dll\dist\index.js:14:12)
[ele]     at Module._compile (internal/modules/cjs/loader.js:967:30)
[ele]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
[ele]     at Module.load (internal/modules/cjs/loader.js:815:32)
[ele]     at Module._load (internal/modules/cjs/loader.js:727:14)
[ele]     at Function.Module._load (electron/js2c/asar.js:769:28)`

**Comment by plus1998** [comment]
https://github.com/durs/node-activex/issues/23
